### ISSUE TITLE
undici fetch has memory leak

### ISSUE THREAD

**Issue by cjh980402** [nodejs/undici#1108]
## Bug Description

When I use node-fetch or axios, then there are no memory leak like under screenshot.
However, I found memory leak when I use undici.fetch.

## Reproducible By

I made request about 50 times~200times then I found that memory leak easily.

## Expected Behavior

there are no memory leak.

## Logs & Screenshots
![image](https://user-images.githubusercontent.com/23624124/142753799-bc57afce-7032-45a2-a2c1-4b3cfc328517.png)

## Environment

Ubuntu 20.04
Node v16.13.0

**Comment by ronag** [comment]
Do you have a repro?

**Comment by cjh980402** [comment]
```js
import { fetch } from 'undici';
import { setTimeout } from 'timers/promises';

const arr = [];
console.log(process.memoryUsage().heapUsed);

for (let i = 0; i < 200; i++) {
    if (i % 10 == 0) {
        console.log(process.memoryUsage().heapUsed);
    }
    for (let j = 0; j < 20; j++) {
        await (await fetch('https://maple.gg/u/%EC%82%BC%EB%9A%9C/sync')).json();
    }
    arr.push((await fetch('https://naver.com')).text());
}

await Promise.all(arr);
console.log(process.memoryUsage().heapUsed);

await setTimeout(10000);

console.log(process.memoryUsage().heapUsed);

await setTimeout(100000);

console.log(process.memoryUsage().heapUsed);
```

It has this result.
![image](https://user-images.githubusercontent.com/23624124/142755753-7137db66-97ee-46e4-baf0-6651b01e6a96.png)
There are some memory leak so finally memory usage is increased.

**Comment by mcollina** [comment]
At first glance, your code behaves more or less how I expected.

(I should probably spend some time in documenting how this happen - however I'm a bit short on time right now).

**Comment by Ethan-Arrowood** [comment]
It would be valuable to try to reproduce this issue with just `undici.request` to isolate the issue to the fetch implementation. 

Some areas within fetch it could happen is in the Body Mixin. We should ensure that once something like `.text()` is awaited that the stream is closed and destroyed.

**Comment by mcollina** [comment]
@Ethan-Arrowood My understanding is that there is no issue. All the requests are still referenced in the array and they can't be collected.

**Comment by ronag** [comment]
@cjh980402 can you try again with the latest release?

**Comment by cjh980402** [comment]
![image](https://user-images.githubusercontent.com/23624124/145418778-398e9d82-a165-4933-976a-34bf7f55c49a.png)
As a result of testing, it is much more stable than the previous version.
However, I will have to wait and see the situation by applying it to the actual application.

**Comment by kyrylkov** [comment]
I can confirm memory leak still present.  The issue is here https://stackoverflow.com/questions/70301834/node-js-non-heap-memory-leaks

As soon as we replace undici with node-fetch, the issue disappears.

**Comment by ronag** [comment]
@kyrylkov: Can you show how you use fetch?

**Comment by kyrylkov** [comment]
@ronag There are multiple cases.  Let me collect some.

**Comment by ronag** [comment]
Can you try with this branch? https://github.com/nodejs/undici/tree/finalization

**Comment by kyrylkov** [comment]
```
  const accessTokenRs = await fetch(URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(params),
  });
  const accessTokenRsJson = await accessTokenRs.json();
```

```
  await fetch(`${url}/lists/${listId}/members/${userHash}`, {
    method: 'DELETE',
    headers: {Authorization: BASIC_AUTH_KEY},
  });
```

```
  const res = await fetch(`${url}/lists/${listId}/members`, {
    method: 'GET',
    headers: {Authorization: BASIC_AUTH_KEY},
  });
  const resJson = await res.json();
```

```
  const res = await fetch(getUrl, {
    method: 'GET',
    headers:{
      'Authorization': `Bearer ${TOKEN}`,
    },
  });
  const text = await res.text();
```

**Comment by kyrylkov** [comment]
> Can you try with this branch? https://github.com/nodejs/undici/tree/finalization

Trying....

**Comment by ronag** [comment]
```  
await fetch(`${url}/lists/${listId}/members/${userHash}`, {
    method: 'DELETE',
    headers: {Authorization: BASIC_AUTH_KEY},
  });
```

You need to consume the response.

**Comment by kyrylkov** [comment]
@ronag Alright. But this cannot cause the leak cause this specific code is called once per week at most.

**Comment by kyrylkov** [comment]
> Can you try with this branch? https://github.com/nodejs/undici/tree/finalization

@ronag GC pauses immediately got at least 2x worse.  Need more time to see if memory leak is still present.

**Comment by kyrylkov** [comment]
@ronag  It's leaking again.

![imagen](https://user-images.githubusercontent.com/6225870/145642492-432edaf6-15f6-4f58-844c-7a01483c2848.png)

**Comment by mcollina** [comment]
The following does not leak memory:

```js
import { fetch } from './index.js';
import { setTimeout } from 'timers/promises';

for (let i = 0; i < 200; i++) {
    if (i % 10 == 0) {
        console.log(process.memoryUsage().heapUsed / 1024 / 1024);
    }
    for (let j = 0; j < 20; j++) {
        await (await fetch('https://www.youtube.com/')).text();
    }
    await (await fetch('https://naver.com')).text();
}
console.log('all req sent');

console.log(process.memoryUsage().heapUsed / 1024 / 1024);

await setTimeout(10000);

console.log(process.memoryUsage().heapUsed / 1024 / 1024);

await setTimeout(100000);

console.log('end');
```

**Comment by kyrylkov** [comment]
@mcollina The leak we're observing is non-heap memory, so my understanding the test above wouldn't show it.

**Comment by mcollina** [comment]
Could you please include a test to reproduce?

What's exactly is the scale of those graphs?

What's the output you're seeing when Node is giving you the out of memory error?

**Comment by kyrylkov** [comment]
@mcollina We don't have a test because it's a big app and we've been chasing non-heap memory leak for weeks.   We seem to isolate the cause to undici fetch vs node-fetch.  Total memory on the chart in the Stack Overflow question is 768MB.   We would need to allow it to crash again to see exact out of memory error.

**Comment by mcollina** [comment]
> We would need to allow it to crash again to see exact out of memory error. The problem is that GC pauses increase 2x-3x as soon as we switch to undici fetch which negatively affects app performance in production. Thus running these tests till out of memory is both time consuming and bad for production application experience overall. We don't have a way to reproduce it outside of production environment.

The finalization branch linked above should fix/resolve it. This is actually pretty bad and possibly a reason to not be spec-compliant @ronag and drop the FinalizationRegistry.

**Comment by kyrylkov** [comment]
@mcollina What we can and will do next week is try to run for 24 hours with undici fetch, recording memory and GC profiles and then another 24 hours with node-fetch.  That should answer lots of questions.

**Comment by mcollina** [comment]
We really need a way to reproduce the problem it we want to fix it.

**Comment by selbstmord** [comment]
hi!

index.js:
```
const { Worker } = require('worker_threads');
const os = require('os');

for (let i = 0; i < 50; i++) {
    const worker = new Worker('./worker.js');
}

setInterval(() => {
    console.log(os.freemem());
}, 1000)
```

worker.js
```
const { fetch } = require("undici");

const main = async () => {
    const res = await fetch("https://jsonplaceholder.typicode.com/posts/1");
    const json = await res.json();

    main();
};

main();
```

result:

```
8510468096
8388669440
8287883264
8248619008
8189575168
8142159872
8103874560
8013099008
7929524224
7844200448
7754084352
7699202048
7761747968
7981531136
8034414592
8069316608
8003137536
7938416640
7885611008
7810236416
7747260416
7687892992
7635963904
7576334336
7512018944
7481835520
7407083520
7363784704
7309643776
7222276096
7145009152
7120793600
7067721728
7029264384
6971269120
6915682304
6861324288
6814982144
6746136576
6654898176
```

memory usage continues to go down

**Comment by mcollina** [comment]
I have tested this for about 10 minutes. Eventually it stabilizes but it degrades pretty sharply.
My understanding is this is somewhat related to the FinalizationGroup handling that we do with fetch() to handle some of the spec-required stuff.

@ronag I think we might want to remove it.

**Comment by ronag** [comment]
But we removed that?

**Comment by mcollina** [comment]
It seems it's still there: https://github.com/nodejs/undici/blob/50fa51bfaa7341ce6b8df72db6ac01fa735b01dd/lib/fetch/request.js#L31.

**Comment by szmarczak** [comment]
@mcollina This one has been added after the removal:

![image](https://user-images.githubusercontent.com/36894700/146250147-c8d3bf59-d342-4e91-ba43-fb328f2f5b96.png)
![image](https://user-images.githubusercontent.com/36894700/146250170-137e845d-6cf5-4e6b-9bd8-34534aec6247.png)

**Comment by mcollina** [comment]
I've tried removing that and it's not the cause or the problem.

Technically it's not a leak but there is some very odd memory behavior that we should fix.

**Comment by ronag** [comment]
I haven't really spent much time optimising allocations. It might also be related to web streams.

**Comment by mcollina** [comment]
I've done a bit of analysis on the following:

```js

const { fetch } = require(".");
const { isMainThread } = require('worker_threads');
const os = require('os');

const main = async () => {
    const res = await fetch("https://jsonplaceholder.typicode.com/posts/1");
    const json = await res.json();

    main();
};

main();
main();
main();
main();
main();

if (isMainThread) {
  setInterval(() => {
      console.log(os.freemem());
  }, 1000)
}
```

I've done an analysis with clinic doctor:

![Screenshot 2021-12-16 at 10 32 24](https://user-images.githubusercontent.com/52195/146345584-3fc08732-0615-4312-a3f1-cece6fae0ccf.png)

heap profiler:

![Screenshot 2021-12-16 at 10 31 38](https://user-images.githubusercontent.com/52195/146345690-0d4fea46-d558-4efe-b6eb-8962b0a26886.png)


(I have not done a bubbleprof analysis because of https://github.com/clinicjs/node-clinic-bubbleprof/issues/388)

**Comment by mcollina** [comment]
I cannot reproduce it directly when using a single process. This is quite interesting:

```js
const { fetch } = require(".");
const { isMainThread } = require('worker_threads');
const os = require('os');

const main = async () => {
    const res = await fetch("https://jsonplaceholder.typicode.com/posts/1");
    const json = await res.json();

    main();
};

main();
main();
main();
main();
main();

if (isMainThread) {
  setInterval(() => {
      console.log(os.freemem());
  }, 1000)
}
```

See
![Screenshot 2021-12-16 at 10 56 38](https://user-images.githubusercontent.com/52195/146349689-e117abf6-3e4c-479a-b423-a15201e00e78.png)

Very interestingly most of the allocations comes from Node core internals:

![Screenshot 2021-12-16 at 10 58 00](https://user-images.githubusercontent.com/52195/146350013-0632d2c9-f6a9-4293-bb7f-78f13be21337.png)


Going back to the multithreaded example, on my system the RSS stabilizes at 1.5 GB of RAM.  My theory for this is that each worker uses about 30 MB of RAM (* 50 = 1.5 GB) because of the activity they need to do - this is consistent for the heap requirement of running a Node.js application.
 
See  https://github.com/nodejs/node/issues/34823 for more details on the topic of the memory requirements of worker threads.

Now, undici fetch() is not gentle on memory allocations and it should probably be optimize to reduce the memory consumption, but this can be closed.

**Comment by ronag** [comment]
Landing this in core will probably help some https://github.com/nodejs/node/pull/41121

**Comment by mcollina** [comment]
Hopefully that'll happen soon.

**Comment by ronag** [comment]
Didn't make it into Node 17.3. Please try later with Node 17.4+ and Undici 4.12.1+

**Comment by ronag** [comment]
Cross that. It **did** make it into node 17.2. Please try with Node 17.2+ and Undici 4.12.1+.

**Comment by selbstmord** [comment]
> heres a good way to reproduce the memory leak
> 
> index.js:
> 
> ```js
> const { Worker } = require('worker_threads');
> const os = require('os');
> 
> for (let i = 0; i < 50; i++) {
> 	new Worker('./worker.js');
> }
> 
> setInterval(() => {
>     console.log(os.freemem());
> }, 1000)
> ```
> 
> worker.js
> 
> ```js
> const { fetch } = require("undici");
> 
> const main = async () => {
>     const res = await fetch("https://jsonplaceholder.typicode.com/posts/1");
>     const json = await res.json();
> 
>     main();
> };
> 
> main();
> ```


i have re-ran this:

https://pastebin.com/wqU6f14F

undici 4.12.1
node v17.3.0

**Comment by selbstmord** [comment]
> I have tested this for about 10 minutes. Eventually it stabilizes but it degrades pretty sharply. My understanding is this is somewhat related to the FinalizationGroup handling that we do with fetch() to handle some of the spec-required stuff.
> 
> @ronag I think we might want to remove it.

basically what was said here still applies

**Comment by awinogrodzki** [comment]
To anyone revisiting this issue in 2024:

I encountered very similar memory leak caused by retained undici requests in `FinalizationRegistry`, both locally and in production environment.

After hours of experimentation I narrowed down the issue to be related with Node.js 20.X on ARM processors. For some reason the leak was evident and caused a linear grow on memory only on Node.js 20 (Disclaimer: Tested only on the latest 20.17 LTS and 20.16). When I downgraded the Node.js to 18 or upgraded to the current, Node.js 22, the leak was no longer present. It also may add to the fact that both my local device and the production server are based on ARM architecture.

If you're researching a leak and run the code on Node.js 20, it's probably a good idea to run a quick test against other Node versions before diving into implementation

Here are example snapshots:

```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6030
Binaries:
  Node: 20.17.0
  npm: 10.8.2
  Yarn: 4.1.0
```
<img width="1021" alt="Screenshot 2024-10-03 at 20 06 16" src="https://github.com/user-attachments/assets/ea8fd7a1-e068-4d18-9d95-25852b4a47f7">



```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6030
Binaries:
  Node: 22.9.0
  npm: 10.8.3
  Yarn: 4.1.0
```
<img width="1022" alt="Screenshot 2024-10-03 at 20 09 47" src="https://github.com/user-attachments/assets/7207f9fa-7400-4d38-af4a-cea0851803fa">

As you see, the memory leak is simply gone after switching from Node 20.17 to 22.9

**Comment by Juraj-Masiar** [comment]
Did anyone experimented with failed requests?
After inspecting my heapsnapshot I've noticed that all (or huge majority) of the leaked URLs were from requests that failed - usually with 404. But even in those cases I'm calling `response.body.cancel()`.

I'm already running Node 22 and Ubuntu 24, so there is not much I could upgrade.
