### ISSUE TITLE
Investigate CI failure

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#1221]
https://github.com/nodejs/undici/runs/5153562802?check_suite_focus=true

**Comment by KhafraDev** [comment]
This is an issue with a node-fetch test that tests AbortController cancellation support. In their test suite, they use a locally hosted server created with `http.createServer`. In the test, they cancel the promise after 100ms, but occasionally the request can succeed before it is canceled.

After a quick look at node-fetch's previous tests, it doesn't look like this is an issue on their side. I'm guessing that there's an issue where a request can be canceled after succeeding, although I didn't bother digging in too deeply.

Sample code (with the error fixed):
```js
import { fetch } from 'undici';
import { createServer } from 'http';
import { once } from 'events';

const server = createServer((req, res) => res.end());
server.listen(3000, () => console.log('done'));
await once(server, 'listening');

let i = 1;
while (i++) {
	try {
		const controller = new AbortController();

		const promise = fetch(`https://www.youtube.com/`, {
			method: 'POST',
			signal: controller.signal,
			headers: {
				'Content-Type': 'application/json',
				body: '{"hello": "world"}'
			}
		});

		setTimeout(() => {
			controller.abort();
		}, 0);

		const test = await promise;
		console.log('did not fail', test);
		break;
	} catch {
		if (i % 1e3 === 0) {
			console.log('did not fail after ' + i + ' tries');
		}
	}
}
```

Since this is an issue with the node-fetch suite, I'm not sure if I should send in a PR here or node-fetch... or both to fix this test. @jimmywarting

**Comment by mcollina** [comment]
I'd go with both.

**Comment by KhafraDev** [comment]
node-fetch tests seem to be outdated since https://github.com/node-fetch/node-fetch/commit/015798edc60f6b480b3df2412f4069df05cb86d5, I'll update them as well.
