### ISSUE TITLE
unexpected behaviours between MockAgent and node's bundled fetch

### ISSUE THREAD

**Issue by panva** [nodejs/undici#1447]
## Bug Description

Intercepting undici's own fetch body works but node's doesn't. This is building on top of the global global dispatcher shipped with 5.2.0 which is then used by Node 18.2.0 bundled fetch.

## Reproducible By

```js
import * as undici from 'undici' // 5.2.0

const mockAgent = new undici.MockAgent()
mockAgent.disableNetConnect()
undici.setGlobalDispatcher(mockAgent)
const pool = mockAgent.get('https://example.com')

pool.intercept({
  path: '/path',
  method: 'POST',
  body(body) {
    console.log(body)
    return true
  }
}).reply(200, { ok: 1 }).times(2)

const url = new URL('https://example.com/path').href

// undici fetch v5.2.0 from node_modules
await undici.fetch(url, {
  method: 'POST',
  body: JSON.stringify({ foo: 'bar' })
})

// undici fetch v5.2.0 from node 18.2.0 global
await globalThis.fetch(url, {
  method: 'POST',
  body: JSON.stringify({ foo: 'bar' })
})
```

The above logs

```
{"foo":"bar"} // undici fetch v5.2.0 from node_modules
Object [AsyncGenerator] {} // undici fetch v5.2.0 from node 18.2.0 global
```

## Expected Behavior

It is expected that the string body is passed into the matching function both times.

## Environment

Node.js 18.2.0
Undici 5.2.0

**Comment by mcollina** [comment]
My bad, I thought I used ```
`Symbol.for()`. Sigh.

**Comment by KhafraDev** [comment]
`Symbol.for` fixes this bug, but now the `options.body` function runs 3 times for 2 mocks.

**Comment by mcollina** [comment]
> `Symbol.for` fixes this bug, but now the `options.body` function runs 3 times for 2 mocks.

why?

**Comment by panva** [comment]
> but now the options.body function runs 3 times for 2 mocks.

Frankly I have noticed the options.body (and even options.header) functions running multiple times before 5.2.0 but I have not payed much attention to it.

**Comment by mcollina** [comment]
@KhafraDev the problem is that `fetch` is using some symbols from "mock" that are going to be different between the bundled fetch and the one in Node.js. Basically we must make sure that `fetch()` does not use any internal symbols.

See https://github.com/nodejs/undici/blob/84c8a027f90cb27a8bfbf162f6c4ab1e0ff5c9a3/lib/fetch/index.js#L1915

Unfortunately I do not have enough time right now to dig deeper into this.

**Comment by KhafraDev** [comment]
Yep, using global symbols (idk the correct term; using `Symbol.for` instead of `Symbol`) fixes the issues, although it would be great to remove the symbols altogether. I had two ideas regarding removing the symbol:

- Async mocking would allow us to resolve the async iterable body instead of using `request.body.source`.
- Check if the current agent is a `MockAgent` instead.

I haven't gotten around to working on either, though. I have a PR that changes the is mock active symbol to using `Symbol.for` but I haven't written tests (no idea how to) and I haven't checked if mock symbols are used elsewhere in fetch where it'd also cause issues.

**Comment by mcollina** [comment]
go for the updated solution, I'll ship a release early next week.
