### ISSUE TITLE
Try all available addresses when connecting to localhost (127.0.0.1 and ::1)

### ISSUE THREAD

**Issue by mcollina** [nodejs/undici#1602]
In node v17 (specifically https://github.com/nodejs/node/pull/39987), we switched the default ordering of dns entries to follow what the OS is providing us vs reordering to put IPv4 addresses always first. This creates quite a few issues for folks as some tools only listen to `127.0.0.1` and not `::1`.

I think we should try multiple addresses when dealing with localhost when establishing a new connection.

Originaklly reported as https://github.com/nodejs/undici/issues/1248.

**Comment by kyrylkov** [comment]
I don't quite understand what localhost has to do with this issue?  In #1248 no localhost was involved.

**Comment by mcollina** [comment]
This issue is based on this comment: https://github.com/nodejs/undici/issues/1248#issuecomment-1054467140. There is something we could improve with `localhost`. As for your problem, we need a repro (feel free to add it to the original issue).

**Comment by bnb** [comment]
FWIW I'm getting this when running `mockAgent.disableNetConnect()` with `fetch`. Might be a different issue (including an "I'm holding it wrong" issue), but wanted to let y'all know _just in case_. Here's my [monorepo](https://github.com/cutenode/nodevu/tree/38d46bee90cd0d20762257f9aa6c99ef9ed341ae) (core is the module that matters here) at the commit that I'm consistently experiencing this issue with. 

I think this should work as a way to get the stack traces quickly: `git clone https://github.com/cutenode/nodevu && cd nodevu && git checkout 38d46bee90cd0d20762257f9aa6c99ef9ed341ae && npm install && npm run test -w core`

**Comment by mcollina** [comment]
Note: this is better solved in nodejs core. https://github.com/nodejs/node/issues/41625

**Comment by jodevsa** [comment]
Hi @mcollina, seems like this haven't been assigned/implemented yet?

**Comment by jodevsa** [comment]
would this fix https://github.com/nodejs/node/pull/44731 solve this issue?

**Comment by mcollina** [comment]
Yes, we'd need to enable that setting once it lands.

**Comment by KhafraDev** [comment]
Should we enable it by default? Agents should be able to set this option already, under `connect` in options.

**Comment by fawazahmed0** [comment]
I faced this issue today in native fetch (v19.5.0) , I had to replace `localhost` to `127.0.0.1` to fix the issue.

**Comment by benwoodward** [comment]
> I faced this issue today in native fetch (v19.5.0) , I had to replace `localhost` to `127.0.0.1` to fix the issue.

this worked for me using _native_ fetch (v18.7.0) inside a `.ts` file in `/lib`, thanks!

**Comment by xuniorss** [comment]
> I faced this issue today in native fetch (v19.5.0) , I had to replace `localhost` to `127.0.0.1` to fix the issue.

Surprisingly, switching from one to the other worked for me. Thanks.

**Comment by Uzlopak** [comment]
@mcollina 
@KhafraDev 
Is this still relevant? autoSelectFamily is already used in undici.

**Comment by yonran** [comment]
I don’t think this should be closed.

@Uzlopak `autoSelectFamily` does not work on a host where loopback has ipv6 but no other interfaces have ipv6 enabled, and you are using glibc, due to a longstanding bug with glibc’s `getaddrinfo` with `AI_ADDRCONFIG` (which `net.connect` adds ([net.js](https://github.com/nodejs/node/blob/v24.5.0/lib/net.js#L1378))) https://sourceware.org/bugzilla/show_bug.cgi?id=14969. For example, inside docker.

Example: if you `server.listen('localhost')` and then `socket.connect('localhost')` in a docker container, the client can’t find the server. This is because `server.listen('localhost')` calls `dns.lookup('localhost', {all:true})` ([net.js](https://github.com/nodejs/node/blob/v24.5.0/lib/net.js#L2196)) which returns ::1 first due to [RFC 6724](https://datatracker.ietf.org/doc/html/rfc6724#section-2.1) and empty /etc/gai.conf rules. So it listens on ipv6 ::1. On the other hand, `socket.connect('localhost')` calls `dns.lookup('localhost', {all:true, hints: dns.ADDRCONFIG}` ([net.js](https://github.com/nodejs/node/blob/v24.5.0/lib/net.js#L1378) and line 1389). Due to the [glibc getaddrinfo ADDRCONFIG loopback bug](https://sourceware.org/bugzilla/show_bug.cgi?id=14969),  ::1 is filtered out before `autoSelectFamily` can try connecting to it.

Example code that listens on localhost and tries to connect to localhost:

```
docker run -e NODE_DEBUG=net --rm node:24 node --input-type=module  -e "
  import {lookup} from 'node:dns/promises';
  import dns from 'node:dns';
  import http from 'node:http';
  import os from 'node:os';
  import {promisify} from 'node:util'

  console.log('os.networkInterfaces():', os.networkInterfaces())

  const server = http.createServer((req, res) => res.end('Hello'));
  await new Promise((resolve, reject) => {
    server.once('listening', resolve);
    server.once('error', reject);
    server.listen(0, 'localhost');
  })
  const address = server.address()
  console.log('listening at', address)

  const fetchUrl = 'http://localhost:' + address.port + '/';
  console.log('performing fetch(',fetchUrl,')')
  const fetchResp = await fetch(fetchUrl)
  await fetchResp.text()
  console.log('fetch succeeded')

  await promisify(http.Server.prototype.close).call(server)
  console.log('success')
"

# Key lines in the output:
NET 1: bind to ::1
NET 1: connect: dns options { family: undefined, hints: 32 }
NET 1: connect/multiple: only one address found, switching back to single connection
NET 1: connect: attempting to connect to 127.0.0.1:45725 (addressType: 4)
TypeError: fetch failed
  [cause]: Error: connect ECONNREFUSED 127.0.0.1:45725
```

Note that musl does not have this bug; `ADDRCONFIG` does NOT filter out the loopback ipv6 address. If you switch to `node:24-alpine`, then there is no exception.

**Comment by Uzlopak** [comment]
@yonran 

I reopened this issue, and i think you have a valid point.  But i wonder if this is something we can solve in undici. Maybe we have to solve it on a different level. It seems incorrect to me to fix this in basically userland. I would actually expect some kind of hint provided by nodejs core.

Something like this? I am right now on the way to the office, and can investigate later regarding this.
https://github.com/nodejs/node/issues/39877

But if we know that we are using musl or glibc then we can actually mitigate the issue maybe in a more performant way? 

I just fear that we implement something in userland, which slows down the whole product just to maybe mitigate one edge case.

**Comment by metcoder95** [comment]
Agree with the statement that this should be downstream to `node` itself; I don't believe this is something that can/should be fixed within `undici`, but we can keep the issue open for visibility.

**Comment by mcollina** [comment]
I don't think this is a problem of undici. Given that glibc bug, I think we should just avoid passing ADDRCONFIG to that specific lookup. Node.js can now handle happy eyeballs everywhere, so we can handle that specific case for which ADDRCONFIG is needed (unreacheable ipv6 addresses).

https://github.com/nodejs/node/blob/931ec10d87730925f0baf10a571330459a1a2fcd/lib/net.js#L1378.

**Comment by metcoder95** [comment]
@mcollina still valid?

**Comment by mcollina** [comment]
Dont think so
