### ISSUE TITLE
Allow request headers option to be string (raw) or Array of strings

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#186]
Allow headers option to be string (raw) or Array of strings. Would make it possible to avoid having to first convert your headers into an object before sending to undici.

```js
if (typeof headers === 'string') {
  this.rawHeaders = headers
  this.host = hasHostHeader(headers
} else if (Array.isArray(headers)) {
  ... opposite of parseHeaders
} else {
  ... current logic
}

```

**Comment by humphd** [comment]
I'm happy to see undici happening, it looks like a great project!  I was hoping to contribute, and was thinking of starting with this issue.  Reading through the code, I had a few questions:

1. For the "string (raw)" case, do you want any processing done on the raw string headers, or just use them untouched as `request.headers`?  For example, do you care if people pass `\n` vs. `\r\n`?  Are errors in formatting the headers the responsibility of the caller?  I ask because there are a bunch of checks in `processHeader()` that could also be applied here.
1. For the "Array of strings" case, I assume you mean passing a complete *field-name: field-value* like `"a: b"`?  If so, how do you want to differentiate between the currently supported "Array of strings" (e.g.,  `['a', 'b', 'c', 'd']`) vs. this new style `['a: b', 'c: d']`?  Should it iterate across and do some regex compare to determine whether this is a complete field vs. name/value?

Thanks for any pointers as to how you want this done.

**Comment by timdp** [comment]
Since a lot of people are probably going to be familiar with the Fetch API, I would propose to mirror that rather than inventing a new format. In particular, its `Headers` class [supports](https://fetch.spec.whatwg.org/#concept-headers-fill) two formats:

* Object for simple cases:
    ```js
    {
      referer: 'https://example.com',
      'x-requested-with': 'undici'
    }
    ```
* Array a la `Object.entries()` for those annoying duplicates:
    ```js
    [
      ['cookie', 'value1'],
      ['cookie', 'value2'],
      ['referer', 'https://example.com']
    ]
	```

Personally, from a client perspective, I've never found it useful to pass a header as `name + ': ' + value`. Let servers deal with string-splitting and whitespace.

**Comment by ronag** [comment]
We actually already support arrays in the following format:

```js
[
  'cookie', 'value1',
  'cookie', 'value2',
  'referer', 'https://example.com'
]
```

**Comment by ronag** [comment]
@humphd Sorry for lack of reply. I seem to have missed your question.

**Comment by humphd** [comment]
@ronag OK, sounds good.

**Comment by timdp** [comment]
> We actually already support arrays in the following format:
> 
> ```js
> [
>   'cookie', 'value1',
>   'cookie', 'value2',
>   'referer', 'https://example.com'
> ]
> ```

Right, forgot about Node's `rawHeaders`. I assume the reasoning behind this rather than an array of tuples/entries is that it produces way fewer objects? V8 would hopefully optimize the hell out of it though.

Personally, I'm not wild about APIs that accept tons of different input formats - because it makes them hard to test, among other things. Therefore, with the `rawHeaders` support in mind, I actually _wouldn't_ mirror the Fetch API after all. That functionality belongs in `undici-fetch` et al.

That said, the translation is going to be a burden. I'm sure I'm biased, but our team has been using Fetch as an abstraction all over the place - and so has Deno, for that matter.

**Comment by Ethan-Arrowood** [comment]
Can I close this issue or convert it into a discussion?
