### ISSUE TITLE
`IncomingHttpHeaders` breaking change from minor update - `v5.15.1` to `>= v.5.17.0`

### ISSUE THREAD

**Issue by r-petit** [nodejs/undici#1920]
## Bug Description

A breaking change happened in version `5.17.0` with the `IncomingHttpHeaders` type. Before this type came from `http` library.
See commit 4bc791f211af430b6529f8eb60c4891db05223ff.

## Reproducible By

Using an older version of `5.17.0` and implement variables that represent the headers. Then upgrade to a version `>= 5.17.0`.

Code example:
```typescript
import type { IncomingHttpHeaders } from 'node:http';
import { Client } from 'undici';

const client = new Client('https://google.com');
const headers: Array<string> | IncomingHttpHeaders | null = {
    'content-type': 'text/html; charset=utf-8'
};

client.request(
	{
		method: 'GET',
		path: '',
		headers // <-- Errors should happend here on version greater or equals to v5.17.0
	}
);
```

## Expected Behavior

The expected behavior is to have either a version update that indicates a breaking change or an export of the type to use this new one.

## Logs & Screenshots

![Screenshot 2023-02-10 at 09 59 22](https://user-images.githubusercontent.com/63579439/218048403-acf5ad4d-f958-4bbe-a021-4b4405def3ed.png)

![Screenshot 2023-02-10 at 10 03 32](https://user-images.githubusercontent.com/63579439/218049487-56465f6b-3a40-4d0c-a0b7-e91f0fbbfce7.png)

## Environment

Node : `v16.17.1`
Typescript : `v4.9.5`
OS : Ventura 13.1 - Apple M2

**Comment by ronag** [comment]
@mcollina wdyt?

**Comment by mcollina** [comment]
A few notes:

1. typescript itself does not follow semver. Therefore it's _best effort_ for the types to follow semver, which has been proven to me multiple times. If there is a breaking change in the types, it's up to you to update your code (because of your choice of using TypeScript).

2. the types of this library needed to be corrected, as they were incorrect to use the types from Node.js core.
