### ISSUE TITLE
Bot UND_ERR_SOCKET

### ISSUE THREAD

**Issue by thiloup** [nodejs/undici#2320]
## Bug Description

We did a BOT on Discord that can open/close channels (like a schedule), the bot works but it cannot be maintained online more than 10 hours. We have to start it manually and it is impossible to have a good BOT.

## Reproducible By

The Bot is stopping, then we can restart it and the bug is starting again, all files are on our Pebble Host serveur.

## Expected Behavior

The bot doesnt stop working and works every time.

## Logs & Screenshots

<02.10 17:17:39 [Bot] node:internal/process/promises:279
02.10 17:17:39 [Bot] triggerUncaughtException(err, true /* fromPromise */);
02.10 17:17:39 [Bot] ^
02.10 17:17:39 [Bot] SocketError: other side closed
02.10 17:17:39 [Bot] at TLSSocket.onSocketEnd (/node_modules/undici/lib/client.js:995:22)
02.10 17:17:39 [Bot] at TLSSocket.emit (node:events:525:35)
02.10 17:17:39 [Bot] at endReadableNT (node:internal/streams/readable:1358:12)
02.10 17:17:39 [Bot] at processTicksAndRejections (node:internal/process/task_queues:83:21) {
02.10 17:17:39 [Bot] code: 'UND_ERR_SOCKET',
02.10 17:17:39 [Bot] socket: {
02.10 17:17:39 [Bot] localAddress: '172.17.0.24',
02.10 17:17:39 [Bot] localPort: 45946,
02.10 17:17:39 [Bot] remoteAddress: '162.159.128.233',
02.10 17:17:39 [Bot] remotePort: 443,
02.10 17:17:39 [Bot] remoteFamily: 'IPv4',
02.10 17:17:39 [Bot] timeout: undefined,
02.10 17:17:39 [Bot] bytesWritten: 367652,
02.10 17:17:39 [Bot] bytesRead: 1327159
02.10 17:17:39 [Bot] }
02.10 17:17:39 [Bot] }
02.10 17:17:39 [PebbleHost] Server shut down (running)
02.10 17:17:39 [PebbleHost] Server stopped

## Environment

Pebble Host,  NodeJS v16.17.0.

**Comment by metcoder95** [comment]
This is not an `undici` error at all but rather implementation details instead. By the error shared, the server seems to be ending the connection due to inactivity (given your context shared), there are several things that can be done, but is often better to both be activated upon action and not sit wasting resources without being used.

As this is not a `bug` I'm closing the issue and marking it as `not planned`, but please open a `Discussion` if you are looking for help or guidance on this 🙂
