### ISSUE TITLE
Breaking change: deprecate `body` on http methods with no defined body semantics

### ISSUE THREAD

**Issue by pxue** [nodejs/undici#2357]
Extending discussion from https://github.com/nodejs/undici/pull/2305#discussion_r1359950673

> if there's no explicit body, or it is a method whose body's semantics are not defined, set `content-length: 0` 

This will be a breaking change:

- All `shouldSendContentLength=false` methods will no longer parse and send any attached body
- `content-length` will be forced to 0 on request

**Comment by metcoder95** [comment]
To give more context around it:

The discussion was going around not allowing to attach bodies to those requests whose doesn't have defined semantics to handle the `body` of a given request (e.g. `GET`, `OPTIONS`, etc.).
Currently `undici` allows these cases, this issue was more to discuss wether we should allow it or now.

> Having second thoughts about it

It might be good to keep it this way, as anyways **it is up to the server to decide what to do** in those scenarios.

Thoughts?

cc @mcollina @ronag @KhafraDev

**Comment by mcollina** [comment]
dispatch should allow it. fetch should follow the spec. I'm on the fence about request.

**Comment by metcoder95** [comment]
Over a quick search, it seems `fetch` spec does not say what to do exactly in these scenarios (unless I'm overlooking it), just specifies redirects. Although `Chrome` throws when attempting to.

For `dispatch` I agree, for `request` I think we can simplify our lives by just keeping it as is; the changes done by #2305 can be the kickoff and keep an eye on it.

**Comment by KhafraDev** [comment]
that part is from the fetch spec, which undici implements. I also think undici should stay the same. If anyone feels differently then this issue can be re-opened.

**Comment by Ethan-Arrowood** [comment]
Agreed - undici can do what it wants HTTP wise if things aren't specified. Fetch should strictly follow spec and browsers.
