### ISSUE TITLE
Docs cleanup

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#517]
- [ ] Cleanup method docs in general (types, formatting etc...).
- [ ] Document `undici.connect`, `undici.update`.
- [ ] Document all errors.

**Comment by ronag** [comment]
@Ethan-Arrowood do you know of a more "standard" way of documenting methods and their signatures? Our current way is a little made up.

**Comment by Ethan-Arrowood** [comment]
Yes, I've based mine of off: https://github.com/electron/electron/blob/master/docs/styleguide.md (there is some tooling based on this guide i hope to use in the far future)

I have some differences though that I used for undici-fetch in regards to argument structure (for example the argument type is wrapped in backticks rather than the name).

**Comment by ronag** [comment]
Feel free to have a go at undici if you ever feel bored. :)

**Comment by Ethan-Arrowood** [comment]
> Feel free to have a go at undici if you ever feel bored. :)

If only I could work on this stuff full time and not have to mix it in with my normal job requirements 😂

**Comment by Ethan-Arrowood** [comment]
https://github.com/Ethan-Arrowood/undici/blob/improve-docs

Since I really want to deepen my understanding of this api I've started organizing the docs.

**Comment by Ethan-Arrowood** [comment]
closed by recent docs updates
