### ISSUE TITLE
Add connect/disconnect events to Agent

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#522]
Similar to how we do for pool but with an extra argument for the origin, e.g.

`emit('connect', pool, origin)`

**Comment by ronag** [comment]
@Ethan-Arrowood

**Comment by ognjenjevremovic** [comment]
Hey @ronag, I see this issue is labeled as a good first issue.
I would be willing to assist on this one if that is ok and if it is not being actively worked on?

I've been following _undici_ for some time now and I'd like to contribute to the project (in any way possible).
It seems to me that this issue would be a good welcoming issue for newcomers.
I would like to ask you for more information about this issue; how should one approach this?

From my understanding the `Agent` should extend the `EventEmitter` class and add support for the `connect` and `disconnect` events, similarly as to how `Pool` does it?

Also, you mentioned that it would be good to pass the `origin` as the 2nd argument to the listeners of the `connect` events; should the `origin` be passed to the listeners of `disconnect` event as well and have the `error` be the 3rd argument?
How may one get a reference to the `origin` from within the `Agent` class (when defining the connect and disconnect methods); I don't see it being used in the class implementation (is it passed as an argument to the constructor?)?

Also, since this can be qualified as a new feature should it be:
* covered with tests,
* documented in the README.md

Apologize if I misunderstood the point of this issue entirely and/or have a wrong clue on the implementation details 🙂 .

**Comment by ronag** [comment]
I don’t think origin is necessary since clients now have the url property.
