### ISSUE TITLE
API Lifecycle Diagram

### ISSUE THREAD

**Issue by Ethan-Arrowood** [nodejs/undici#532]
I think something that would be really valuable for this library is if we can provide a detailed diagram explaining the lifecycle of a request with this library. It would be really helpful for both contributors and users. The diagram should detail things like when certain events are fired as well as how it all corresponds to the Node.js event loop. We should have one for the Client class and its respective methods, another for Pool (which can reference the Client one), and then maybe another for Agent which is based on the Pool and Client ones.

I'd be happy to collaborate on this, but I'd definitely need some help from @ronag or @mcollina. I'm getting better at understanding the event loop but I'm not all the way there yet 😅

**Comment by mcollina** [comment]
I'll be happy to answer questions, go for it!

**Comment by Ethan-Arrowood** [comment]
I'm planning to start by just logging the call stack of a simple call to Client and going from there. I'll ping when I have something 😄

**Comment by Ethan-Arrowood** [comment]
@ronag or @mcollina can you explain why something like `Client.request` is implemented as it is? A good starting point would be: Why does `RequestHandler` extend `AsyncResource`? Could the `client-request.js` file be implemented directly on the `Client` class? If not, why? 

Additionally, could you share some details on how `Client.dispatch` works? I'm trying my best to understand the queuing system but its quite difficult. If theres any external resources that describes this pattern feel free to link to those as well. Thank you!

**Comment by mcollina** [comment]
We inherit from `AsyncResource` to be compatible with AsyncLocalStorage and the rest of async_hooks-based systems. If we didn't, a user will lose context when the response comes out of the request.

**Comment by Ethan-Arrowood** [comment]
>  rest of async_hooks-based systems. If we didn't, a user will lose context when the response comes out of the request.

Can you dig a bit deeper on this point?

**Comment by mcollina** [comment]
async_hooks use `AsyncResource` to track the asynchronous flow of execution. Thanks to this, APMs and applications could store information that is context-dependent without passing it as an argument. It's a mechanism similar to a thread local in Java or .NET.

As an example, a socket is an `AsyncResource`, as well as our http parser. Every `AsyncResource` has a _parent_: in this way we can pass on the context between various asynchronous steps. 

In Undici, we reuse our connections, and each one of them is in the chain of context that created it. When we send a request, we "cross over" from the originating context (the one that is sending the request) to the one of the socket.
When we receive a response, it will not have the correct `AsyncResource`. In order to restore the context correctly, Undici wraps the responses inside an `AsyncResource`.

---

Overall all of that are implementation details. I don't think it should reach the docs.

**Comment by Ethan-Arrowood** [comment]
Thats perfect! Thank you for the detailed explanation. 

--- 

I'm making progress on understanding `Client.dispatch` - i'll follow up when I have a more specific question soon

**Comment by Ethan-Arrowood** [comment]
Everything is a state machine 😱
