### ISSUE TITLE
Don't copy entire root when building Docker

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#638]
Instead of

```
COPY . .
```

Could we just copy the relevant files & folders?

**Comment by ronag** [comment]
The dockerignore is probably sufficient if this is complicated.

**Comment by ronag** [comment]
What exactly does the Docker file do and what does it need?

**Comment by dnlup** [comment]
The `Dockerfile` uses a `Debian` image to install in a consistent way `wasm` dependencies (the SDK, so you don't have to set up anything on your machine if you don't want to) and to compile the `wasm` binary.

[`npm ci`](https://docs.npmjs.com/cli/v7/commands/npm-ci) is a command that performs a clean install by:

* removing `node_modules` if present
* installing dependencies using the `package-lock.json`

This method is faster than `npm i`, provided that a lock file is present. Otherwise, the installation would fail. I thought it was a good assumption because we are running the build script locally, in an environment where the lock file should be present.

**Comment by mcollina** [comment]
Let's just move it to `npm i`

**Comment by dnlup** [comment]
I opened a PR  to switch to `npm i`. Do we want to remove the `.dockerignore` file then? Do you think it's better to specify the assets to copy in the `Dockerfile` directly?
