### ISSUE TITLE
Allow overriding `headersTimeout` and `bodyTimeout` on request basis

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#666]
Right now these are always determined by the client constructor argument.

**Comment by artur-ma** [comment]
Just a question, to understand how do u see it

allowing it per request means there should be validation on each request I guess (e.g check if integer)
does it affect performance? 

another one, here on http2 thread ( https://github.com/nodejs/undici/issues/547)  u said that that new http2Client should be implemented, does it mean each client should validate its own options, even if there is some code duplication (since constructor options are validated on client level), or should it move to another place?
