### ISSUE TITLE
Add same origin redirect support for Client and Pool 

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#686]
See how it's done in `Agent`. If redirect then create a `RedirectHandler` wrapper around the original dispatch handler.

**Comment by MetCoder95** [comment]
Hi! I just started reading the code in order to start working on this issue 🙂 

I'm really new with the code as I'm just starting but I figured out the following: In order to do the same as `Agent` does (i.e. wrapping the `handler` with `RedirectHandler`), is a need to pass an instance of `Agent`, which means that might need to be modified as well.
Also, we should make the redirect once the response is received and parsed from the remote host or based on the config var as `Agent` does? My first assumption is the second option but would like to double-check 🙂

**Comment by ronag** [comment]
You don't need to pass an instance of Agent. That's only needed for cross origin.

**Comment by MetCoder95** [comment]
But it is done in this way by `Agent` see: https://github.com/nodejs/undici/blob/e7e393a095c9e9bfa34db9dee18e668dbe8cb939/lib/agent.js#L181

and also `RedirectHandlers` uses it:
https://github.com/nodejs/undici/blob/e7e393a095c9e9bfa34db9dee18e668dbe8cb939/lib/handler/redirect.js#L8

Or am I looking into the wrong place?

**Comment by ronag** [comment]
You can pass a pool or client as `agent` there. Should probably be renamed to `dispatcher`.

**Comment by MetCoder95** [comment]
Oh, that's true, they share the same shape. I missed that, thanks! I can rename it as part of the PR
