### ISSUE TITLE
FormData streaming

### ISSUE THREAD

**Issue by ronag** [nodejs/undici#963]
Looking at the spec it doesn't look like `FormData` should be streamed in neither the encode nor the decode case, i.e. it's all encoded/decoded into memory as fast as possible without any back-pressure.

1. Am I misreading the spec?
2. Is this a problem we need to fix? If yes, then how?

**Comment by ronag** [comment]
@szmarczak @Ethan-Arrowood @mcollina

**Comment by mcollina** [comment]
I think it's rather inefficient to do this :(.

**Comment by ronag** [comment]
Sorry, I'm not sure what you mean? It's inefficient the way it's done now or it's inefficient to try and change it?

**Comment by ronag** [comment]
Could it be that browser actually write it to file?

**Comment by octet-stream** [comment]
Maybe I have missed something, but where may I see where's the spec prohibits FormData from being streamed?

I agree with @mcollina that streams will be the more efficient way to send FormData, because you extract its entries as you read that stream and do not have to put the whole thing into memory, this makes more sense in Node.js...

This is how I done it in `form-data-encoder`:
1. You put a reference to a FormData instance to its (the FormDataEncoder) constructor. It only creates a boundary string, then iterates through given instance to calculate the size of the body to send.
2. When an HTTP client will send a request - you start to read through the encoder and only then it will perform the encoding.

**Comment by ronag** [comment]
>  but where may I see where's the spec prohibits FormData from being streamed?

Which directions are you referring to? client -> server? If you read the algorithm in the spec it does not take back pressure into consideration. https://fetch.spec.whatwg.org/#concept-bodyinit-extract

**Comment by octet-stream** [comment]
> client -> server?

Exactly. How you would implement the `formData` method to decode it back is the other question. I'm talking only about the way you encode it to send to the server. I see that the spec has `extract a body` concept, but I don't really see if it prohibits from using streams, or blobs (as you did it in current implementation), or something else.

If you need to know how browsers done this, then maybe just look at their implementations:

- https://github.com/WebKit/WebKit/tree/main/Source/WebCore/Modules/fetch
- https://github.com/chromium/chromium/tree/master/third_party/blink/renderer/core/fetch
- https://github.com/mozilla/gecko-dev/tree/master/dom/fetch

I am not familiar with C++ so can't understand much if this :<

**Comment by ronag** [comment]
https://github.com/nodejs/undici/pull/961/commits/eac31d6a82eab97e52552cc23e0e6f667dc3ce82

**Comment by ronag** [comment]
So now only server -> client is an issue...

**Comment by ronag** [comment]
The only way I see to solve the server -> client case is to buffer the data through a `File`... the `FormData` API is unfortunately synchronous.

**Comment by ronag** [comment]
@mcollina wdyt? leave as is and close? I think this is something that the spec needs to solve not us.

**Comment by mcollina** [comment]
We should document this.
